{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flutterchat.module",
    "module": "flutter_release",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.9.aar",
          "url": "flutter_release-1.0.9.aar",
          "size": 5600672,
          "sha512": "98a1144e142bf9cbcc7f423879fa60d6a5a56cf723d138243861667629e73dbcf738fd61f15c1f90f98867716dde85a815004bb643dac3ca5fbfcc9607cf1978",
          "sha256": "25c1fac56aac2b4fdf1eccf7cb285fec7e2a7e6680a6544b48614a8579970e58",
          "sha1": "dead594591b1044cf8846477f405421d18fdfe48",
          "md5": "0fcb2c2dabec57ef1b790969e21122aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.9.aar",
          "url": "flutter_release-1.0.9.aar",
          "size": 5600672,
          "sha512": "98a1144e142bf9cbcc7f423879fa60d6a5a56cf723d138243861667629e73dbcf738fd61f15c1f90f98867716dde85a815004bb643dac3ca5fbfcc9607cf1978",
          "sha256": "25c1fac56aac2b4fdf1eccf7cb285fec7e2a7e6680a6544b48614a8579970e58",
          "sha1": "dead594591b1044cf8846477f405421d18fdfe48",
          "md5": "0fcb2c2dabec57ef1b790969e21122aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.9-sources.jar",
          "url": "flutter_release-1.0.9-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.9-javadoc.jar",
          "url": "flutter_release-1.0.9-javadoc.jar",
          "size": 261621,
          "sha512": "a6a28c13d34d0cbd9b3da17efc630398c41287b6fc91db4a7fb8557feacea219e7085eb382ed22de5d895601b3ea1a3e453f468abc01ea4de60bdb69ef6757bd",
          "sha256": "8b13d9003a3a6591efe3e2557440bf5bbb44f51a92f713f7d76025a4a64bdf8d",
          "sha1": "49fec4207dfeb05a609eec51a5787fa0ce5a66b2",
          "md5": "ed69a154ff23d7c5d4ae05104914e8c0"
        }
      ]
    }
  ]
}
