{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flutterchat.module",
    "module": "flutter_release",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.9.aar",
          "url": "flutter_release-1.0.9.aar",
          "size": 5580392,
          "sha512": "a031f9a240cf4ad3bc720b3e2b71196fdde92514b648b68daf8c3cc8359c4725e75b483e2f4604f518618903bae40c52fbf5dbedef989c40923385a05b12dc71",
          "sha256": "a5c7661ed0870c4672ecb8f194949ca77302ff0dfedcda13efc31074871cd45f",
          "sha1": "363839277af0770881d7871f40486fa08e84a53f",
          "md5": "87930759db66634aa73bc462f56e7429"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.9.aar",
          "url": "flutter_release-1.0.9.aar",
          "size": 5580392,
          "sha512": "a031f9a240cf4ad3bc720b3e2b71196fdde92514b648b68daf8c3cc8359c4725e75b483e2f4604f518618903bae40c52fbf5dbedef989c40923385a05b12dc71",
          "sha256": "a5c7661ed0870c4672ecb8f194949ca77302ff0dfedcda13efc31074871cd45f",
          "sha1": "363839277af0770881d7871f40486fa08e84a53f",
          "md5": "87930759db66634aa73bc462f56e7429"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.9-sources.jar",
          "url": "flutter_release-1.0.9-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.9-javadoc.jar",
          "url": "flutter_release-1.0.9-javadoc.jar",
          "size": 261621,
          "sha512": "a6a28c13d34d0cbd9b3da17efc630398c41287b6fc91db4a7fb8557feacea219e7085eb382ed22de5d895601b3ea1a3e453f468abc01ea4de60bdb69ef6757bd",
          "sha256": "8b13d9003a3a6591efe3e2557440bf5bbb44f51a92f713f7d76025a4a64bdf8d",
          "sha1": "49fec4207dfeb05a609eec51a5787fa0ce5a66b2",
          "md5": "ed69a154ff23d7c5d4ae05104914e8c0"
        }
      ]
    }
  ]
}
