{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flutterchat.module",
    "module": "flutter_release",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.4.aar",
          "url": "flutter_release-1.0.4.aar",
          "size": 5536006,
          "sha512": "42e8390176ffa32853235a73698dbc0fe3223105ffa02c398a341bf6835b17757329d2c9e4f8f9f7faa5b1321bdd2ed473385d5318a8dd0a043c928e41492d4c",
          "sha256": "071f867094d6b2d4c0419e7920ecc374cca8f2d70aca1d77c1f04f68ea952fe2",
          "sha1": "e85424e0507a3c6df4bda744eeb402c0a2f91d68",
          "md5": "7c0b3b1c9c3717b64e40064006ac9593"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.4.aar",
          "url": "flutter_release-1.0.4.aar",
          "size": 5536006,
          "sha512": "42e8390176ffa32853235a73698dbc0fe3223105ffa02c398a341bf6835b17757329d2c9e4f8f9f7faa5b1321bdd2ed473385d5318a8dd0a043c928e41492d4c",
          "sha256": "071f867094d6b2d4c0419e7920ecc374cca8f2d70aca1d77c1f04f68ea952fe2",
          "sha1": "e85424e0507a3c6df4bda744eeb402c0a2f91d68",
          "md5": "7c0b3b1c9c3717b64e40064006ac9593"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.4-sources.jar",
          "url": "flutter_release-1.0.4-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.4-javadoc.jar",
          "url": "flutter_release-1.0.4-javadoc.jar",
          "size": 261620,
          "sha512": "6d4b2ecacb190d679211c6a557e9b480262f8d58fd3a10169ed8764e3e908ff611a3e6a2137575288a06ab3ffd6abd8b9c21fb5c1c0a3ebde2eb48c61a603006",
          "sha256": "5fd2c63b9e369e57ad61664d575c38dcc32293e6d9d4b19e809676219ed4a1c3",
          "sha1": "5e4604907c9028b97dea0cb56508d6d3eccbf96d",
          "md5": "1d55f19eda34f08fa8c17e16218c8dcd"
        }
      ]
    }
  ]
}
